### ISSUE TITLE
Error: `MSVCP140.DLL` Not Found

### ISSUE THREAD

**Issue by Naturlands** [CoolSpy3/hmmm-language-support#1]
the code execution cannot proceed because MSVCP140.DLL was not found

**Comment by Naturlands** [comment]
the code execution cannot proceed because MSVCP140.DLL was not found

**Comment by CoolSpy3** [comment]
Hmmmm.... I'm not sure why *this* extension specifically would cause that error. Try (re)installing the [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) [[Citation](https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-and-msvcp140dll-missing-in-windows/caf454d1-49f4-4d2b-b74a-c83fb7c38625)].

If that doesn't work, I'll probably need more information to diagnose the bug:
1. What were you doing when the error occurred?
2. Where did the error show up: log file, popup, etc.?
3. Why do you believe that this extension caused the error?
4. If possible, please provide a list of steps I can use to reproduce the error locally.
5. Please attach your extension host log and the HMMM Binary Language Server and HMMM Language server logs.

Instructions to find the relevant log files:
Method 1: In VSCode, go to `View > Output`, select the relevant logs from the dropdown and copy them.
Method 2:
1. Open the logs directory. This can be done by opening the Command Palette and selecting `Developer: Open Extension Logs Folder`. This should open `%LOCALAPPDATA%/Code/logs/<TIMESTAMP>/window<NUMBER>/exthost` (I don't know the path on non Windows OSes).
2. The relevant files are `exthost.log`, `output_logging_<TIMESTAMP>/<NUMBER>-HMMM Binary Language Server.log`, and `output_logging_<TIMESTAMP>/<NUMBER>-HMMM Language Server.log` (If they exist).
